name: jubal_lite
description: Jubal — pure audio experience.
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  just_audio: ^0.9.42

dev_dependencies:
  flutter_lints: ">=4.0.0 <7.0.0"

flutter:
  uses-material-design: true
